### ISSUE TITLE
next steps v0.1

### ISSUE THREAD

**Issue by eins78** [NTS/portfolio#1]
- this just about these 2 folders: [projects](https://github.com/NTS/portfolio/tree/master/2.projects) and [curationals](https://github.com/NTS/portfolio/tree/master/3.curatorials)
- everything is imported into this stacey folder structure
- info does **not** need to in stacey format (`project.yml`), just simple or slightly formatted text (`TextEdit.app`)
- nothing needs to be deleted except duplicate pictures, best quality stays. 'misc' stuff can just go into subfolders
## Tasks
- [ ] make a first layout draft from existing content -- @darkovelazquez 
- [ ] move pictures from NTS Archive -- @NTS
- [ ] collect/move (all) the texts -- @NTS ?
- [ ] clean texts -- @NTS ?
- [ ] edit texts -- @NTS ?
- [ ] check NTS/PhD@postdoc (A5!) -- @NTS 
- [ ] CV Latex sources -- @eins78
